### ISSUE TITLE
想要一份你论文中提到的网络结构yaml文件（trans+bifpn）

### ISSUE THREAD

**Issue by Salary-only-17k** [Rvosuke/MSFT-YOLO#2]
你好，最近我在做工业表面质检面的工作，看了你的MSFT-YOLO论文，对我有启发，对你的网络结构很感兴趣，同时也遇到点问题。
想要一份你论文中提到的网络结构yaml文件（trans+bifpn）。
还有不知道你还有当初的训练tensorboard日志吗？想要一份。

**Comment by Salary-only-17k** [comment]
找到了yolov5_SwinV2.yaml 等等

**Comment by Rvosuke** [comment]
可以切换到msft分支，其中的./yolov5-master1102中有部分yaml文件
